# Generated by Django 6.0.5 on 2026-06-01 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key (UUID) for the NGO', primary_key=True, serialize=False)),
                ('external_api_id', models.CharField(blank=True, help_text='External API ID if integrated', max_length=255, null=True)),
                ('name', models.CharField(help_text='Name of the NGO', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ of the NGO (formatted or unformatted)', max_length=18, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the NGO', null=True)),
                ('focus_area', models.CharField(blank=True, help_text='Focus area of the NGO', max_length=255, null=True)),
                ('current_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current evaluation score', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating if the NGO is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
                'db_table': 'ngo',
            },
        ),
    ]
