# Generated by Django 6.0.6 on 2026-06-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_campaign_destination_campaign_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
